---
title: Sharmaluna1988.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: assets/images/avatar1.jpg
- scope:
    path: _pages
  values:
    layout: page
name: জানালা
description: আলাপ ও অপলাপসমূহ
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
url: https://sharmaluna1988.github.io
baseurl: "/"
disqus: demowebsite
email: wowthemesnet@gmail.com
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  sal:
    name: শর্মা লুনা
    site: https://www.sharmaluna.com
    avatar: assets/images/luna-profile.JPG
    bio: ""
    email:
    twitter:

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: শর্মা লুনা
      avatar: assets/images/luna-profile.JPG

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax

markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
