---
title: Sharmaluna1988.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: luna
    avatar: assets/images/luna-profile.JPG
- scope:
    path: _pages
  values:
    layout: page
name: জানালা
description: আলাপ ও অপলাপসমূহ
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
url: https://sharmaluna1988.github.io
baseurl: "/"
disqus: jaanaalaa
email: sharmaluna1988@gmail.com
mailchimp-list: https://github.us11.list-manage.com/subscribe/post?u=2088efa7f9eb0edbdd5711c20&amp;id=07af44c99d&amp;f_id=00369ee0f0
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  luna:
    name: শর্মা লুনা
    site: https://www.sharmaluna.com
    avatar: assets/images/luna-profile.JPG
    bio: ''
    email: 
    twitter: 
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
sass:
  sass_dir: _sass
  style: compressed
default_image: https://source.unsplash.com/featured/?abstract
